### ISSUE TITLE
ValueError: tile cannot extend outside image

### ISSUE THREAD

**Issue by kihosuh** [arnavkj1995/face_inpainting#2]
Hi I keep getting an error like this. I am on Ubuntu 16.04. Can you please help me?

```
Traceback (most recent call last):
  File "preprocess_train_images.py", line 175, in <module>
    face_part = imresize(face_part, [128,128])
  File "/home/kiho/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/kiho/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 554, in imresize
    im = toimage(arr, mode=mode)
  File "/home/kiho/anaconda3/lib/python3.6/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/kiho/anaconda3/lib/python3.6/site-packages/scipy/misc/pilutil.py", line 407, in toimage
    image = Image.frombytes(mode, shape, strdata)
  File "/home/kiho/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2331, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/kiho/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 782, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image
```

**Comment by lantuxin** [comment]
Because some face can not be detected. You can delete these images.
